// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmQpugujCB6nG0jCu0BhqxlVDgokOW1RM',
    appId: '1:1020742181933:web:3d386f45484e5672bd04a4',
    messagingSenderId: '1020742181933',
    projectId: 'ienergy-app',
    authDomain: 'ienergy-app.firebaseapp.com',
    storageBucket: 'ienergy-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZb3ruROvCQaZdX8K4wzTrtU-BX9iIdas',
    appId: '1:1020742181933:android:3d32289ac11a59efbd04a4',
    messagingSenderId: '1020742181933',
    projectId: 'ienergy-app',
    storageBucket: 'ienergy-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvWR_ehTWvwCdGJ_aUIloA33atnqJgNiQ',
    appId: '1:1020742181933:ios:4cdf1de497803356bd04a4',
    messagingSenderId: '1020742181933',
    projectId: 'ienergy-app',
    storageBucket: 'ienergy-app.appspot.com',
    iosClientId: '1020742181933-hddcfpep9jj08891dggnn1jrfefsccv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ienergyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvWR_ehTWvwCdGJ_aUIloA33atnqJgNiQ',
    appId: '1:1020742181933:ios:4cdf1de497803356bd04a4',
    messagingSenderId: '1020742181933',
    projectId: 'ienergy-app',
    storageBucket: 'ienergy-app.appspot.com',
    iosClientId: '1020742181933-hddcfpep9jj08891dggnn1jrfefsccv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ienergyApp',
  );
}
